M48
; DRILL file {KiCad 5.99.0-unknown-64d35ecebc~127~ubuntu20.04.1} date Sat May  1 12:49:20 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-05-01T12:49:20+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.99.0-unknown-64d35ecebc~127~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0248
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1063
%
G90
G05
T1
X5.8781Y-4.86
T2
X5.6419Y-4.86
X5.8781Y-4.86
T3
X5.4Y-2.85
X6.1Y-2.85
T0
M30
