M48
; DRILL file {KiCad 5.99.0-unknown-8f3343b9e3~128~ubuntu20.04.1} date Thu Jun  3 23:09:31 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-06-03T23:09:31+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.99.0-unknown-8f3343b9e3~128~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X5.8911Y-2.2825
X5.8911Y-4.3825
T0
M30
